* 2016-Feb-16-Wednesday:
** From 9:30 AM TO 11:00 AM :
 - Today I have read about VLEAD and Virtual Labs from online is available at [[http://community.virtual-labs.ac.in/w/index.php/What_is_VLEAD%3F][here]] 
* What is VLEAD?
 - VLEAD (Virtual Labs Engineering and Architecture Division), based in IIIT-Hyderabad campus, is one of the several teams working on the =Virtual Labs= project.
 - VLEAD’s mandate is to design and architect the implementation framework for Virtual Labs, providing all kinds of infrastructure support and services to lab 
   developers.Of the twelve participating institutes of the project which includes IITs of Delhi, Bombay, Kanpur, Kharagpur, Madras, Guwhati, Roorkee, 
   IIIT Hyderabad, NITK Surathkal, COE Pune, Dayalbagh Institute and Amrita Institute, VLEAD team from IIIT Hyderabad has taken the responsibility of being the 
   Central Engineering Team in hosting the labs and providing infrastructure service and support to lab developers.
* What is Virtual Labs project?
 - Virtual Labs project is an initiative of the Ministry of Human Resource Development (MHRD), a Government of India sponsored project, under the 
   National Mission on Education through Information and Communication Technology (NMEICT).
 - The project’s goal is to provide quality Engineering and Science lab experience to all the students of the country with as minimum requirements as a 
   computer system and an internet connection from the learners. 

** From 11:00 AM TO 01:00 PM :
 - I have worked with sripathi to explain about BASE1, BASE2, BASE3, BASE4, servers
 - Base1:= Base1 is a server machine, which has staging server, It is used to test software or website. Which we installed Operating System is CentOS and OpenVZ used couple of containers installed of our physical system
 - Base2:= Base2 is a server machine, Which is used for Production phase (Keep it running or using a websites), Which we installed Operating is CentOS and OpenVZ used couple of containers installed of our physical system.
 - Base3:=Base3 is a server machine, Which is used for Production phase (Keep it running or using a websites), Which we installed Operating is CentOS and OpenVZ used couple of containers installed of our physical system.
 - Base4:= Base4 is a server machine, Which is used to testing softwares or websites (i.e catch the errors and correct the errors), Which we installed Operating is CentOS and OpenVZ used couple of containers installed of our physical system.
 
** From 2:30 AM TO 06:00 PM :
 - Today I gone through about Logwatch and Install Logwatch, configure, and taken articles from online is availble at [[https://devops.profitbricks.com/tutorials/install-and-configure-logwatch/][here]]
* Logwatch:
 - Logwatch is a simple log analysis tool provided with most Linux distributions. A daily scheduled cron job parses the various system logs and sends a
   log summary to the root user or a defined destination email address.
** Requirements
 - Red Hat Enterprise Linux (RHEL) or Debian based distributions (CentOS, Fedora, Ubuntu, etc).
*** Install logwatch:
 - To install logwatch follow below command 
#+begin_example
yum install logwatch
#+end_example
*** Configure Logwatch:
 - The email report will be delivered to the local root user by default. To specify an alternate email address, 
   create a new file called =/etc/logwatch/conf/logwatch.conf= and add the following line.
#+begin_example
MailTo = user@example.com
#+end_example
 - The default log summary email will be in standard text format. The email format can be changed to HTML by setting the Format value in the same logwatch.conf file.
#+begin_example
Format = html
#+end_example
 - The email sender can be changed from Logwatch to another local user or email address by setting the MailFrom value.
#+begin_example
MailFrom = user@example.com
#+end_example
 - The summary includes a list of services that list can be found in the =/usr/share/logwatch/scripts/services/= directory. 
   Those services can be excluded from the summary by prepending a hyphen to the Service name value.
#+begin_example
Service = All
Service = "-ftpd-xferlog"
#+end_example
 - The service All value can also be replaced by a specific name if only that service log should be analyzed.
 - Additional customizations to =logwatch.conf= can be found in the default global configuration file.
#+begin_example
/usr/share/logwatch/default.conf/logwatch.conf
#+end_example
 - The logwatch process can be run manually with a variety of parameters for testing purposes.
#+begin_example
/usr/sbin/logwatch --mailto user@example.com --format html --service secure
#+end_example
