* 2016-Feb-12-Satarday
** From 10:30 AM TO 05:30 PM :
- Today I have taken Version Control System and GIT. And read various articles from online and practise git commands those are 
* Version Control System:
 - A system that records changes to a file over time so you can recall specific vesions later.
 - A way to keep track of changes to files
 - Between multiple developers
 - A record of who did what, when

** Advantages of Version Control Sytem:
+ Backup and Restore
+ Sync with multiple computers
+ Working in a team
+ Safely create and test new features

** Types of VCS:
+ GIT
+ SVN(Subversion)
+ Bazaar

* GIT:
- GIT is a open source distributed Version Control System. It tracks content such as files and directories.

* Github:
- GitHub, is a web-page on which you can publish your Git repositories and collaborate with other people.

*** Git Branches:
 - A branch in Git is simply a lightweight movable pointer to one of these commits. 
   The default branch name in Git is master. As you initially make commits, you're given a master branch that points to the last commit you made. 
   Every time you commit, it moves forward automatically.
 - A branch, at its core, is a unique series of code changes with a unique name. Each repository can have one or more branches.
   to create branch, git branch -a

*** GIT Basic Commands:
 - Configure your user and email for Git via the following command.
#+begin_example
git config --global user.name "Firstname Lastname"
#+end_example
 - configure the email address
#+begin_example
git config --global user.email "your.email@example.org" 
#+end_example
 - git-clone - Clone a repository into a new directory
#+begin_example
git clone <repositry>
#+end_example
 - git init :
 + which is used to initialize the project or repositry.
#+begin_example
git init <repositry>
#+end_example
 - git status:
 + which is used to know the status of project or repositry.
#+begin_example
git status
#+end_example
 - git add filename:
 + filename will be added to git verrsion control
#+begin_example
git add sample
#+end_example
 - git commit -m "commit message":
 + which is used to mension the message according to the your task done.
#+begin_example
git commit -m "Hello today my task is done"
#+end_example
 - git push:
 + This will upload load to online repositry.
#+begin_example
git push
#+end_example
 - git log:
 + which is used to display of the commit.
#+begin_example
git log
#+end_example
- git checkout commitid:
+ which is used to navigate to the specified commitid
#+begin_example
git checkout 1215...
#+end_example
