* 2016-Feb-28-Monday:
** From 9:30 AM TO 06:00 PM :
 - Today I took various web-servers such as DHCP-Server, BIND(DNS)-Server and I installed DHCP and BIND(DNS) Servers on CentOS. I have read about those servers and taken various articles from online.
* DHCP(Dynamic Host Configuration Protocol):
 - Dynamic Host Configuration Protocol (DHCP) is a network protocol that automatically assigns TCP/IP information to client machines.
   Each DHCP client connects to the centrally located DHCP server, which returns the network configuration (including the IP address, gateway, and DNS servers)
   of that client. 
** Why use DHCP ?
 - DHCP is useful for automatic configuration of client network interfaces. When configuring the client system, you can choose DHCP instead of specifying an 
   IP address, netmask, gateway, or DNS servers. The client retrieves this information from the DHCP server. DHCP is also useful if you want to change the
   IP addresses of a large number of systems. Instead of reconfiguring all the systems, you can just edit one configuration file on the server for the new set of IP addresses.
   If the DNS servers for an organization changes, the changes happen on the DHCP server, not on the DHCP clients. When you restart the network or reboot the clients,
   the changes go into effect.
 - If an organization has a functional DHCP server correctly connected to a network, laptops and other mobile computer users can move these devices from office to office. 
** Advantages of DHCP-Server:
 - There is no need to manually configure each client with an IP address.
 - You don't need to keep a record of the IP addresses that you have assigned.
 - You can automatically assign a new IP address if you move a client to a different subnet.
* Installing DHCP server on Centos:
- Update yum repositories and packages by typing the below command
#+begin_example
[root@localhost ~]# yum update
#+end_example
- Install dhcp server and client using the below command
#+begin_example
[root@localhost ~]# yum install dhcp
#+end_example
* DNS-Server 
- Domain Name System (or Service or Server), an Internet service that translates domain names into IP addresses. Because domain names are alphabetic,
  they're easier to remember. The Internet however, is really based on IP addresses. Every time you use a domain name, therefore,
  a DNS service must translate the name into the corresponding IP address.
   * EX:= To find the IP address of www.example.com. We use command as below
#+begin_example
nslookup www.example.com
#+end_example
The above command will give the ip address associated with =www.example.com= using DNS server.
* BIND(DNS)-Sever:
- BIND stands for Berkley Internet Naming Daemon. Which is the most common program used for maintaining a name server on Linux.
** Advantages of DNS-Server:
- DNS can be configured to allow dynamic secure updates, enhancing the security of your DNS infrastructure.
- No need to memorise numbers.
- Domain names makes / gives a kind of sense to hyper links when a name is given instead of a string of numbers .
- Easy for categorising,archiving and inturn helping ( to an extent ) search engines.
* Installing BIND on DNS Servers:
- Update yum repositories and packages by typing the below command
#+begin_example
[root@localhost ~]# yum update
#+end_example
- Install BIND(DNS) Server using the below command
#+begin_example
[root@masterdns ~]# yum install bind* -y
#+end_example

